DROP TABLE IF EXISTS PERSONS;
CREATE TABLE PERSONS(ID INT PRIMARY KEY, NAME VARCHAR(255));
DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(ID INT PRIMARY KEY, NAME VARCHAR(255));
DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES(ID INT PRIMARY KEY, NAME VARCHAR(255));
DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(ID INT PRIMARY KEY, NAME VARCHAR(255), AUTHOR_ID INT, GENRE_ID INT, FOREIGN KEY (AUTHOR_ID) references AUTHORS(ID), FOREIGN KEY (GENRE_ID) references GENRES(ID));