application:
  version: 2.0
spring:
  datasource:
    url: jdbc:postgresql://188.227.18.141:5432/lib
    username: sergya
    password: otus
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
#  h2:
#    console:
#      enabled: true
#      path: localhost:8080/h2-console/